sacloud/iaas-api-go

- .github/workflows/release.yaml
- .github/workflows/tests.yaml
- .github/workflows/textlint.yaml
- .gitignore
- .golangci.yml
- .goreleaser.yml
- .textlintignore
- .textlintrc
- AUTHORS
- LICENSE
- Makefile
- README.md
- go.mod
- version.go
libsacloud v2からプロジェクト構造のみを移行
- v0 or v1からになるためv2ディレクトリは廃止
- その他ソースコードの構成は未定なため最低限のファイルだけ移行
- MakefileやGitHub Actionsなどの追加
> 初期プロジェクト構造の追加

- go.mod
- go.sum
- helper/api/caller.go
- helper/defaults/defaults.go
- helper/power/power.go
- helper/power/power_test.go
- helper/wait/simple_state_waiter.go
- helper/wait/wait.go
- state.go
- state_functions.go
- state_test.go
https://github.com/sacloud/sacloud-go/pull/16 でsacloud-goに切り出したwaitパッケージを使うように修正
IaaS側固有事情として以下のような実装を残した。
- Availability/InstanceStatusによるステートのチェック
- リソース作成直後の404 NotFound対応
> iaas.StateWaiterをsacloud-go/pkg/waitパッケージを使うように切り替え

- helper/api/options.go
helper/api利用時にsacloud/api-client-goのどのバージョンを利用しているか判別できるようにデフォルトのUserAgentを修正する。
Note: Optionsの利用方法によってUserAgentが反映されない場合(例えばOptionsFromProfile()やOptionsFromEnv()だけ使う場合)があるが、その場合はhelper/apiでエクスポートしているvar `UserAgent`を直接参照してもらうことで対応する。
> helper/api: UserAgentにsacloud/api-client-goのUserAgentを含める

- customize_envelope.go
- fake/ops_auto_scale.go
- fake/zz_api_ops.go
- fake/zz_api_ops_test.go
- fake/zz_resources.go
- fake/zz_store.go
- internal/define/apis.go
- internal/define/auto_scale.go
- internal/define/fields.go
- internal/define/names/resource_name.go
- naked/auto_scale.go
- stub/zz_api_stubs.go
- test/auto_scale_op_test.go
- trace/otel/zz_api_tracer.go
- trace/zz_api_tracer.go
- zz_api_ops.go
- zz_api_transformers.go
- zz_apis.go
- zz_envelopes.go
- zz_models.go
- zz_result.go
オートスケールのCRUD+L操作+αを行うためのAPIを追加
```go
type AutoScaleAPI interface {
Find(ctx context.Context, conditions *FindCondition) (*AutoScaleFindResult, error)
Create(ctx context.Context, param *AutoScaleCreateRequest) (*AutoScale, error)
Read(ctx context.Context, id types.ID) (*AutoScale, error)
Update(ctx context.Context, id types.ID, param *AutoScaleUpdateRequest) (*AutoScale, error)
UpdateSettings(ctx context.Context, id types.ID, param *AutoScaleUpdateSettingsRequest) (*AutoScale, error)
Delete(ctx context.Context, id types.ID) error
Status(ctx context.Context, id types.ID) (*AutoScaleStatus, error)
}
```
> オートスケールAPI

- internal/define/auto_scale.go
- internal/define/fields.go
- test/auto_scale_op_test.go
- zz_models.go
オートスケールの閾値関連の設定をiaas.AutoScale直下ではなく、nakedと同じCPUThresholdScaling配下に移動する
> AutoScale: iaas.AutoScaleCPUThresholdScalingの導入

- internal/define/models.go
- naked/vpc_router.go
- test/vpc_router_op_test.go
- zz_models.go
closes #33 
Note: breaking-changeとなるためVPCルータのSettings.SiteToSiteIPsecVPNを利用していたクライアントは修正が必要。
> VPCルータ: サイト間VPN接続パラメータ

- helper/query/archive_find_by_ostype.go
- helper/query/archive_find_by_ostype_test.go
from: https://github.com/sacloud/terraform-provider-sakuracloud/issues/912
パブリックアーカイブと同じタグを持つアーカイブが存在した場合に意図したアーカイブ以外がヒットする場合があった問題を修正
> query.FindArchiveByOSTypeでScopeを考慮するように修正

- fake/functions.go
- helper/query/archive_find_by_ostype.go
- helper/query/archive_find_by_ostype_test.go
- ostype/filter_criteria.go
closes #83 
- DATA RACEを防ぐために実行時にostype.ArchiveCriteriaを変更しないようにする
- FakeドライバーでScopeの比較がうまくいかない問題を修正するために比較前に型を揃える対応
> query.FindArchiveByOSTypeの問題を修正

- internal/define/models.go
- test/server_op_test.go
- test/vpc_router_op_test.go
- transformer_test.go
- zz_models.go
omitemptyが付いていると他にパラメータがない場合にエラーとなる。また、True->Falseへの変更も行えない。
このためomitemptyを除去し常にリクエストに含めるようにする
> VPCRouterのTypeStringFlag項目からomitemptyを除去

- internal/define/auto_backup.go
- internal/define/fields.go
- zz_models.go
#104 のデグレ
#104でフィールド名を修正した際に誤って対象外のフィールド(BackupSpanWeekdays)も変更した問題の修正
> fix: フィールド名修正 -> BackupSpanWeekdays

- example_test.go
Go Exampleで `Scope: "shared"` のようにハードコードを利用していますが、
`iaas-api-go/types` で `Scopes.Shared` を提供しているので、そちらを利用するようにしました。
In example_test.go, the serverCRUD test uses a hard-coding like `Scope: "shared"`.
But the `iaas-api-go/types` package provides the constant `types.Scopes.Shared`.
So this PR replaces the hard-coding to the constant, for avoiding the confusion.
Signed-off-by: Drumato <drumato43@gmail.com>
> doc: using `types.Scopes.Shared` instead of raw string literal

- go.mod
- go.sum
- helper/api/options.go
- api-client-go@v0.2.3へのアップデート
- api.DefaultOptionWithProfileでいくつかのデフォルト値が環境変数/プロファイルより優先されていた問題を修正
> プロファイル周りの改善

- test/database_op_test.go
- types/database_version.go
データベースアプライアンスではバージョン指定がオプショナルになっており、省略した場合は最新版となる。
このため従来ソース上に持っていたバージョン情報定義が不要となったため除去する。
> データベースアプライアンスのバージョン周りの定義を除去

- .golangci.yml
- naked/database.go
from: https://github.com/sacloud/terraform-provider-sakuracloud/issues/988
`Tag`フィールドで文字列/数値が混在するためinterface{}で受け取るようにする。
> データベースアプライアンスの/statusで特定のフィールドの値が文字列/数値混在する問題への対応

- naked/database.go
冗長化プランの場合のみ以下のようなJSONが返され、型不一致エラーが発生する。
```
"Interfaces": [
[],
{
"VirtualIPAddress": "192.168.0.254"
}
]
```
UnmarshalJSONの実装で`[]`が渡されてもエラーにしないように修正。
> データベースアプライアンス冗長化プランでの型不一致エラーの修正

- naked/proxylb.go
- test/proxylb_op_test.go
BackendHttpKeepAliveはsafe or aggressiveの2値のみで空にすることはないためomitemptyを付与して対応
> fix: ELB.BackendHttpKeepAliveの省略対応

- fake/ops_enhanced_db.go
- internal/define/enhanced_database.go
- stub/zz_api_stubs.go
- test/enhanced_db_op_test.go
- trace/otel/zz_api_tracer.go
- trace/zz_api_tracer.go
- zz_api_ops.go
- zz_api_transformers.go
- zz_apis.go
- zz_envelopes.go
- zz_models.go
- zz_result.go
#197 の補完
- config(MaxConnectionなど)用の参照用エンドポイントを追加
- テストにおいてデータベース名にアルファベットのみ用いるように修正
> EDBのconfigエンドポイントの追加

- fake/ops_enhanced_db.go
- internal/define/enhanced_database.go
- internal/define/fields.go
- naked/enhanced_db.go
- test/enhanced_db_op_test.go
- types/enhanced_db_region.go
- types/enhanced_db_type.go
- zz_models.go
⚠️ breaking-changeを含みます(LABプロダクト)
- MariaDBに対応
- 東京リージョンに対応
- 従来は固定だったDatabaseType/DatabaseRegionを作成時に指定可能に
- DatabaseType/DatabaseRegionをstring -> 独自型に
> Enhanced DBでのMariaDB対応 & 東京リージョン対応

- types/auth.go
types.ExternalPermissionにおいてAppRunと高火力DOKの権限を持っているかの判断をするためのヘルパーfuncを追加
> ExternalPermission: supports AppRun and KoukaryokuDOK

- .github/workflows/release.yaml
- .goreleaser.yml
https://github.com/sacloud/iaas-api-go/pull/317 によりgoreleaser v2が使われるようになったため関連する設定項目を修正する
https://github.com/sacloud/webaccel-api-go/pull/56 を参考にしています。
- goreleaserのconfigをv2に対応
- GitHub ActionsでGoのバージョン判定にgo.modを利用するように変更
> goreleaser v2に対応

- types/sim_network_operators.go
no issue
セキュアモバイルでのdocomo回線廃止に対応する
https://www.sakura.ad.jp/corporate/information/announcements/2025/03/14/1968218982/
なお、このPR時点では価格表APIなどにDocomo表記が残っている部分があるために一部 `docomo`記述が残っている。
no
> docomo回線提供終了対応

- naked/container_registry.go
no issue
コンテナレジストリでユーザーの情報を更新する際、passwordフィールドをnullにするとエラーになる問題を修正。
omitemptyを除去し常にフィールドをリクエストに含めるようにした。
no
> Always include password field in ContainerRegistryUser
